# --- Core Parameters ---
defaults:
  - _self_
  - model: nequip
  - dataset: ase
  - trainer: nequip

run:
  - train
  - test

# --- Dataset ---
dataset:
  file_name: ./Aspirin_cropped.xyz
  r_max: 5.0  # Always use float for r_max
  chemical_symbols: &chemical_symbols [C, O, H]
  validation_split: 0.1
  test_split: 0.1
  transforms:
    - _target_: nequip.data.transforms.NeighborListTransform
      r_max: ${dataset.r_max}
    - _target_: nequip.data.transforms.ChemicalSpeciesToAtomTypeMapper
      chemical_symbols: ${dataset.chemical_symbols}

# --- Model ---
model:
  type_names: *chemical_symbols
  r_max: ${dataset.r_max}
  num_layers: 4
  l_max: 1
  num_features: 64
  num_bessels: 8
  polynomial_cutoff_p: 6
  pair_potential:
    _target_: nequip.nn.pair_potential.ZBL
    units: metal
    chemical_species: *chemical_symbols

# --- Training ---
training:
  loss_coeffs:
    forces: 1.0
    energy: 1.0
  metrics_components:
    - forces_mae
    - energy_mae
  optimizer:
    lr: 0.01
    weight_decay: 0.0

trainer:
  max_epochs: 1000
  accelerator: gpu
  logger:
    _target_: lightning.pytorch.loggers.CSVLogger
    name: aspirin_log
    save_dir: ./results
  callbacks:
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val_loss
      patience: 20
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      filename: best_model
      save_top_k: 1
